/**
 * @file Plugin Constants
 */

export const FETCH_PLUGINS_REQUEST = 'FETCH_PLUGINS_REQUEST';
export const FETCH_PLUGINS_SUCCESS = 'FETCH_PLUGINS_SUCCESS';
export const FETCH_PLUGINS_FAILURE = 'FETCH_PLUGINS_FAILURE';

export const FETCH_PLUGIN_REQUEST = 'FETCH_PLUGIN_REQUEST';
export const FETCH_PLUGIN_SUCCESS = 'FETCH_PLUGIN_SUCCESS';
export const FETCH_PLUGIN_FAILURE = 'FETCH_PLUGIN_FAILURE';