/**
 * @file Plugin Constants
 */

export const FETCH_PLUGINS_REQUEST = 'FETCH_PLUGINS_REQUEST';
export const FETCH_PLUGINS_SUCCESS = 'FETCH_PLUGINS_SUCCESS';
export const FETCH_PLUGINS_FAILURE = 'FETCH_PLUGINS_FAILURE';

export const FETCH_RECENTLY_UPDATED_REQUEST = 'FETCH_RECENTLY_UPDATED_REQUEST';
export const FETCH_RECENTLY_UPDATED_SUCCESS = 'FETCH_RECENTLY_UPDATED_SUCCESS';
export const FETCH_RECENTLY_UPDATED_FAILURE = 'FETCH_RECENTLY_UPDATED_FAILURE';