/**
 * @file Plugin Constants
 */

export const FETCH_RECENTLY_UPDATED_REQUEST = 'FETCH_RECENTLY_UPDATED_REQUEST';
export const FETCH_RECENTLY_UPDATED_SUCCESS = 'FETCH_RECENTLY_UPDATED_SUCCESS';
export const FETCH_RECENTLY_UPDATED_FAILURE = 'FETCH_RECENTLY_UPDATED_FAILURE';